Feature/specify steamdir
414n/protonsh pull request #1
Opened 2020-03-11 05:52 UTC by triffid

I don't have anything in my default steam app directory (~/.steam/steam/steamapps), this patch allows me to specify other locations to look.

Ideally we can grab the list of locations from steam settings somewhere.

2020-03-11 19:49 UTC, 414n commented
Hi @triffid,

thanks for your contribution. I just left a single review note about a variable name.
After that is dealt with, I'll gladly merge this! :+1:

2020-03-12 01:26 UTC, triffid commented
Hmm I can't see your note anywhere, did github eat it or is its visibility private or something?

2020-03-12 08:46 UTC, 414n requested changes

2020-03-12 08:46 UTC, 414n commented on protonsh.sh
> +steamdir="${STEAMDIR:-$HOME/.steam/steam/SteamApps}"
I'd prefer a more specific variable name pair, like `steamAppsDir`/`STEAM_APPS_DIR`.
Do you mind changing it?

2020-03-12 08:47 UTC, 414n commented
> Hmm I can't see your note anywhere, did github eat it or is its visibility private or something?

Sorry, my fault. It seems like it was kept there as a draft until now. Do you see it?

2020-03-12 08:51 UTC, triffid commented
There, how's this?

2020-03-12 09:27 UTC, merged

2020-03-12 09:28 UTC, 414n commented
Perfect, thank you very much!